const RUBI_IMAGE_ROOT = "/images/tenants/rubi";

/**
 * Public, migration-authorized Rubí content. Operational demo data (customers,
 * sales and inventory) intentionally lives outside this module.
 */
export const RUBI_BRAND_CONTENT = {
  ids: {
    accountId: "rubi-account-id",
    tenantId: "rubi-id",
    stockLocationId: "rubi-main-location-id",
  },
  accountName: "Rubí",
  tenant: {
    slug: "rubi",
    name: "Rubí Joyería",
    shortName: "Rubí",
    defaultCurrency: "ARS",
    timeZone: "America/Argentina/Tucuman",
    enabled: true,
  },
  storeProfile: {
    brandName: "Rubí Joyería",
    contactEmail: "rubi.joyeria803@gmail.com",
    phone: "3816776136",
    addressLine: "Mendoza",
    addressNumber: "803",
    city: "San Miguel de Tucumán",
    province: "Tucumán",
    postalCode: null,
    countryCode: "AR",
  },
  storefrontSettings: {
    publicUrl: "https://rubijoyeria.empretienda.com.ar",
    isPublished: true,
    contactFormEnabled: true,
    showPrices: true,
    allowNegativeStock: false,
    defaultCatalogSort: "FEATURED",
    catalogColumnsDesktop: 4,
  },
  theme: {
    logoUrl: null,
    faviconUrl: null,
    primaryColor: "#74263A",
    secondaryColor: "#312A2B",
    accentColor: "#B39155",
    backgroundColor: "#F8F6F1",
    surfaceColor: "#FFFFFF",
    textColor: "#292526",
    mutedTextColor: "#706869",
    headingFont: "Merriweather",
    bodyFont: "Lora",
    borderRadius: "0rem",
    sourceTemplateColor: "#EA3A3A",
    announcementEnabled: true,
    announcementText: "ENVÍO GRATIS a todo San Miguel de Tucumán",
    announcementUrl: "https://www.instagram.com/rubijoyerias",
  },
  contactChannels: [
    {
      key: "whatsapp",
      channelType: "WHATSAPP",
      value: "3816776136",
      url: "https://wa.me/5493816776136",
      enabled: true,
      sortOrder: 0,
    },
    {
      key: "instagram",
      channelType: "INSTAGRAM",
      value: "rubijoyerias",
      url: "https://www.instagram.com/rubijoyerias",
      enabled: true,
      sortOrder: 1,
    },
    {
      key: "facebook",
      channelType: "FACEBOOK",
      value: "rubijoyerias",
      url: "https://www.facebook.com/rubijoyerias",
      enabled: true,
      sortOrder: 2,
    },
    {
      key: "tiktok",
      channelType: "OTHER",
      label: "TikTok",
      value: "@rubijoyerias",
      url: "https://www.tiktok.com/@rubijoyerias",
      enabled: true,
      sortOrder: 3,
    },
  ],
  copy: {
    seoDescription:
      "Esta es la tienda online de RUBI JOYERIA! Ingresá y conocé nuestra amplia variedad de productos.",
    financingLabel: "Consulte financiamiento",
  },
  assets: {
    hero: {
      url: `${RUBI_IMAGE_ROOT}/hero/coleccion-rubi.webp`,
      alt: "Collar y aros dorados con piedras color rubí sobre una base de piedra clara",
    },
    goldJewelry: {
      url: `${RUBI_IMAGE_ROOT}/products/joyas-oro.webp`,
      alt: "Anillos y cadena dorados sobre una superficie de piedra clara",
    },
    silverJewelry: {
      url: `${RUBI_IMAGE_ROOT}/products/plata-y-reloj.webp`,
      alt: "Aros y reloj plateados sobre piedra oscura",
    },
  },
} as const;

export const RUBI_CATEGORY_CONTENT = [
  { key: "general", slug: "general", name: "General", parentKey: null, sortOrder: 0 },
  { key: "oro-18kt", slug: "oro-18kt", name: "Oro 18kt", parentKey: null, sortOrder: 1 },
  { key: "oro-18kt-anillos", slug: "oro-18kt-anillos", name: "Anillos", parentKey: "oro-18kt", sortOrder: 0 },
  { key: "oro-18kt-pulseras", slug: "oro-18kt-pulseras", name: "Pulseras", parentKey: "oro-18kt", sortOrder: 1 },
  { key: "oro-18kt-dijes", slug: "oro-18kt-dijes", name: "Dijes", parentKey: "oro-18kt", sortOrder: 2 },
  { key: "oro-18kt-cadenas", slug: "oro-18kt-cadenas", name: "Cadenas", parentKey: "oro-18kt", sortOrder: 3 },
  { key: "oro-18kt-aros", slug: "oro-18kt-aros", name: "Aros", parentKey: "oro-18kt", sortOrder: 4 },
  { key: "oro-18kt-alianzas", slug: "oro-18kt-alianzas", name: "Alianzas", parentKey: "oro-18kt", sortOrder: 5 },
  { key: "oro-18kt-abridores", slug: "oro-18kt-abridores", name: "Abridores", parentKey: "oro-18kt", sortOrder: 6 },
  { key: "plata", slug: "plata", name: "Plata", parentKey: null, sortOrder: 2 },
  { key: "plata-anillos", slug: "plata-anillos", name: "Anillos", parentKey: "plata", sortOrder: 0 },
  { key: "plata-anillos-iniciales", slug: "plata-anillos-iniciales", name: "Iniciales", parentKey: "plata-anillos", sortOrder: 0 },
  { key: "plata-anillos-plata-y-oro", slug: "plata-anillos-plata-y-oro", name: "Plata y oro", parentKey: "plata-anillos", sortOrder: 1 },
  { key: "plata-anillos-hombre", slug: "plata-anillos-hombre", name: "Hombre", parentKey: "plata-anillos", sortOrder: 2 },
  { key: "plata-anillos-bulgari", slug: "plata-anillos-bulgari", name: "Bulgari", parentKey: "plata-anillos", sortOrder: 3 },
  { key: "plata-anillos-piedras", slug: "plata-anillos-piedras", name: "Piedras", parentKey: "plata-anillos", sortOrder: 4 },
  { key: "plata-anillos-frutilla", slug: "plata-anillos-frutilla", name: "Frutilla", parentKey: "plata-anillos", sortOrder: 5 },
  { key: "plata-anillos-san-benito", slug: "plata-anillos-san-benito", name: "San Benito", parentKey: "plata-anillos", sortOrder: 6 },
  { key: "plata-dijes", slug: "plata-dijes", name: "Dijes", parentKey: "plata", sortOrder: 1 },
  { key: "acero", slug: "acero", name: "Acero", parentKey: null, sortOrder: 3 },
  { key: "relojes", slug: "relojes", name: "Relojes", parentKey: null, sortOrder: 4 },
  { key: "outlet", slug: "outlet", name: "Outlet", parentKey: null, sortOrder: 5 },
] as const;

/**
 * Names and prices mirror the authorized storefront capture. The available
 * WebP files are representative catalog imagery, not exact per-SKU photos.
 */
export const RUBI_PRODUCT_CONTENT = [
  {
    key: "ag-1-7-a-roseta",
    slug: "ag-1-7-a-roseta",
    name: "AG1,7 (A) Roseta",
    sku: null,
    price: 605_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-anillos"],
    imageUrl: `${RUBI_IMAGE_ROOT}/products/joyas-oro.webp`,
    imageAlt: "Anillos y cadena dorados sobre una superficie de piedra clara",
    imageIsRepresentative: true,
    featured: true,
    published: true,
  },
  {
    key: "as-13",
    slug: "as-13",
    name: "AS13",
    sku: null,
    price: 20_000,
    currency: "ARS",
    description: null,
    material: "Plata",
    categoryPath: ["plata", "plata-anillos", "plata-anillos-san-benito"],
    imageUrl: `${RUBI_IMAGE_ROOT}/products/plata-y-reloj.webp`,
    imageAlt: "Aros y reloj plateados sobre piedra oscura",
    imageIsRepresentative: true,
    featured: true,
    published: true,
  },
  {
    key: "as-24",
    slug: "as-24",
    name: "AS24",
    sku: null,
    price: 36_000,
    currency: "ARS",
    description: null,
    material: "Plata",
    categoryPath: ["plata", "plata-anillos", "plata-anillos-san-benito"],
    imageUrl: `${RUBI_IMAGE_ROOT}/products/plata-y-reloj.webp`,
    imageAlt: "Aros y reloj plateados sobre piedra oscura",
    imageIsRepresentative: true,
    featured: true,
    published: true,
  },
  {
    key: "pg-5-9-roca",
    slug: "pg-5-9-roca",
    name: "PG5.9 (Roca)",
    sku: null,
    price: 2_000_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-pulseras"],
    imageUrl: `${RUBI_IMAGE_ROOT}/products/joyas-oro.webp`,
    imageAlt: "Anillos y cadena dorados sobre una superficie de piedra clara",
    imageIsRepresentative: true,
    featured: true,
    published: true,
  },
  {
    key: "dg-0-5-acc",
    slug: "dg-0-5-acc",
    name: "DG0,5 (acc)",
    sku: null,
    price: 175_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-dijes"],
    imageUrl: `${RUBI_IMAGE_ROOT}/hero/coleccion-rubi.webp`,
    imageAlt: "Collar y aros dorados con piedras color rubí sobre una base de piedra clara",
    imageIsRepresentative: true,
    featured: false,
    published: true,
  },
  {
    key: "dg-0-3-mz",
    slug: "dg-0-3-mz",
    name: "DG0,3 (Mz)",
    sku: null,
    price: 110_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-dijes"],
    imageUrl: `${RUBI_IMAGE_ROOT}/hero/coleccion-rubi.webp`,
    imageAlt: "Collar y aros dorados con piedras color rubí sobre una base de piedra clara",
    imageIsRepresentative: true,
    featured: false,
    published: true,
  },
  {
    key: "dg-0-3-g",
    slug: "dg-0-3-g",
    name: "DG0,3 (G)",
    sku: null,
    price: 110_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-dijes"],
    imageUrl: `${RUBI_IMAGE_ROOT}/hero/coleccion-rubi.webp`,
    imageAlt: "Collar y aros dorados con piedras color rubí sobre una base de piedra clara",
    imageIsRepresentative: true,
    featured: false,
    published: true,
  },
  {
    key: "hg-1-1-ga",
    slug: "hg-1-1-ga",
    name: "HG1,1 (Ga)",
    sku: null,
    price: 385_000,
    currency: "ARS",
    description: null,
    material: "Oro 18K",
    categoryPath: ["oro-18kt", "oro-18kt-aros"],
    imageUrl: `${RUBI_IMAGE_ROOT}/hero/coleccion-rubi.webp`,
    imageAlt: "Collar y aros dorados con piedras color rubí sobre una base de piedra clara",
    imageIsRepresentative: true,
    featured: false,
    published: true,
  },
] as const;

export type RubiBrandContent = typeof RUBI_BRAND_CONTENT;
export type RubiCategoryContent = (typeof RUBI_CATEGORY_CONTENT)[number];
export type RubiProductContent = (typeof RUBI_PRODUCT_CONTENT)[number];
