<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BackgroundServices\" />
    <Folder Include="Contexts\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Extensions\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Services\" />
    <Folder Include="Refit\" />
  </ItemGroup>

</Project>
